/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.truckLogisticApp.view;

import com.truckLogisticApp.model.OrderModel;
import com.truckLogisticApp.model.UserModel;
import com.truckLogisticApp.model.TruckModel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aarohnkhadka
 */
public class LogisticsApp extends javax.swing.JFrame {

    
    private java.awt.CardLayout cardLayout;
    private List<UserModel> userList;
    private List<TruckModel> truckList;
    
    /**
     * Creates new form LogisticsApp
     */
    public LogisticsApp() {
        initComponents();
        initializeLayout();
        initializeData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        logoIngLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        credentialPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PickUptextField = new java.awt.TextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        dropOffTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        topPanel2 = new javax.swing.JPanel();
        logoIngLabel3 = new javax.swing.JLabel();
        logoutButton2 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        removeUserButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        updateInfoButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        loginPanel = new javax.swing.JPanel();
        truckImgLabel = new javax.swing.JLabel();
        credentialPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameTextField = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        adminCheckBox = new javax.swing.JCheckBox();
        logoIngLabel = new javax.swing.JLabel();

        userPanel.setBackground(new java.awt.Color(0, 0, 133));

        topPanel.setBackground(new java.awt.Color(25, 34, 75));

        logoIngLabel1.setBackground(new java.awt.Color(0, 0, 133));
        logoIngLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/truckLogisticApp/resources/logo.png"))); // NOI18N
        logoIngLabel1.setText("jLabel5");

        logoutButton.setBackground(new java.awt.Color(255, 255, 227));
        logoutButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(25, 33, 75));
        logoutButton.setText("LOG OUT");
        logoutButton.setBorderPainted(false);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addComponent(logoIngLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(25, 25, 25))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(logoIngLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 133));

        credentialPanel1.setBackground(new java.awt.Color(84, 84, 84));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 227));
        jLabel5.setText("CHOOSE YOUR");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 227));
        jLabel6.setText("LOCATION");

        PickUptextField.setBackground(new java.awt.Color(255, 255, 227));
        PickUptextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        PickUptextField.setText("");
        PickUptextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PickUptextFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 227));
        jLabel7.setText("Pick Up Location:");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 227));
        jLabel8.setText("Drop Off Location:");

        jButton2.setBackground(new java.awt.Color(255, 255, 227));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(25, 33, 75));
        jButton2.setText("Get Rates");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        dropOffTextField.setBackground(new java.awt.Color(255, 255, 227));
        dropOffTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropOffTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout credentialPanel1Layout = new javax.swing.GroupLayout(credentialPanel1);
        credentialPanel1.setLayout(credentialPanel1Layout);
        credentialPanel1Layout.setHorizontalGroup(
            credentialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credentialPanel1Layout.createSequentialGroup()
                .addGroup(credentialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(credentialPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(credentialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(dropOffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PickUptextField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentialPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        credentialPanel1Layout.setVerticalGroup(
            credentialPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credentialPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PickUptextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropOffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(634, Short.MAX_VALUE)
                .addComponent(credentialPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(credentialPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 0, 133));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Pick Up Location", "Drop Location", "Payment"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Your History", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About Us", jPanel4);

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        adminPanel.setBackground(new java.awt.Color(0, 0, 133));

        topPanel2.setBackground(new java.awt.Color(25, 34, 75));

        logoIngLabel3.setBackground(new java.awt.Color(0, 0, 133));
        logoIngLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/truckLogisticApp/resources/logo.png"))); // NOI18N
        logoIngLabel3.setText("jLabel5");

        logoutButton2.setBackground(new java.awt.Color(255, 255, 227));
        logoutButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        logoutButton2.setForeground(new java.awt.Color(25, 33, 75));
        logoutButton2.setText("LOG OUT");
        logoutButton2.setBorderPainted(false);
        logoutButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanel2Layout = new javax.swing.GroupLayout(topPanel2);
        topPanel2.setLayout(topPanel2Layout);
        topPanel2Layout.setHorizontalGroup(
            topPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel2Layout.createSequentialGroup()
                .addComponent(logoIngLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton2)
                .addGap(25, 25, 25))
        );
        topPanel2Layout.setVerticalGroup(
            topPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(logoIngLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addComponent(logoutButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.setBackground(new java.awt.Color(254, 254, 227));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 133));

        jPanel1.setBackground(new java.awt.Color(0, 0, 143));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Sex", "Age"
            }
        ));
        jScrollPane2.setViewportView(userTable);

        removeUserButton.setBackground(new java.awt.Color(255, 255, 227));
        removeUserButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        removeUserButton.setForeground(new java.awt.Color(25, 33, 75));
        removeUserButton.setText("Remove User");
        removeUserButton.setBorderPainted(false);
        removeUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserButtonActionPerformed(evt);
            }
        });

        addUserButton.setBackground(new java.awt.Color(255, 255, 227));
        addUserButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        addUserButton.setForeground(new java.awt.Color(25, 33, 75));
        addUserButton.setText("Add User");
        addUserButton.setBorderPainted(false);
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        updateInfoButton.setBackground(new java.awt.Color(255, 255, 227));
        updateInfoButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        updateInfoButton.setForeground(new java.awt.Color(25, 33, 75));
        updateInfoButton.setText("Update Info");
        updateInfoButton.setBorderPainted(false);
        updateInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(removeUserButton)
                        .addGap(82, 82, 82)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(updateInfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(updateInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Users", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "UserID", "Date", "Pick Up", "Drop"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Recent Bookings", jPanel5);

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addComponent(topPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));

        loginPanel.setBackground(new java.awt.Color(0, 0, 133));
        loginPanel.setMaximumSize(null);

        truckImgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/truckLogisticApp/resources/truck.png"))); // NOI18N

        credentialPanel.setBackground(new java.awt.Color(84, 84, 84));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 227));
        jLabel1.setText("LOGIN TO YOUR");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 227));
        jLabel2.setText("ACCOUNT");

        usernameTextField.setBackground(new java.awt.Color(255, 255, 227));
        usernameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        usernameTextField.setText("");
        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 227));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 227));
        jLabel4.setText("Password");

        passwordTextField.setBackground(new java.awt.Color(255, 255, 227));
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(255, 255, 227));
        loginButton.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(25, 33, 75));
        loginButton.setText("LOGIN");
        loginButton.setBorderPainted(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        adminCheckBox.setForeground(new java.awt.Color(242, 242, 227));
        adminCheckBox.setText("Admin Account");
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout credentialPanelLayout = new javax.swing.GroupLayout(credentialPanel);
        credentialPanel.setLayout(credentialPanelLayout);
        credentialPanelLayout.setHorizontalGroup(
            credentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentialPanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(credentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(credentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentialPanelLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(113, 113, 113))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentialPanelLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(73, 73, 73))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, credentialPanelLayout.createSequentialGroup()
                            .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25)))
                    .addGroup(credentialPanelLayout.createSequentialGroup()
                        .addGroup(credentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminCheckBox)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(credentialPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        credentialPanelLayout.setVerticalGroup(
            credentialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(credentialPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(adminCheckBox)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        logoIngLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/truckLogisticApp/resources/logo.png"))); // NOI18N
        logoIngLabel.setText("jLabel5");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(truckImgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(credentialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoIngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoIngLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(truckImgLabel)
                        .addGap(178, 178, 178))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(credentialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(82, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(loginPanel, "LoginPage");
        getContentPane().add(userPanel, "UserPanel");
        getContentPane().add(adminPanel, "AdminPanel");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoginPage");
    }
    
    private void initializeData() {
        userList = new LinkedList<>();

        // Adding users with orders
        registerUser(new UserModel(1, "Alice", "Female", 25, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(101, "Kathmandu", "Pokhara"),
                new OrderModel(102, "Lalitpur", "Bhaktapur")
            ))
        ));

        registerUser(new UserModel(2, "Bob", "Male", 30, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(103, "Biratnagar", "Bhairahawa"),
                new OrderModel(104, "Dhangadhi", "Nepalgunj")
            ))
        ));

        registerUser(new UserModel(3, "Charlie", "Male", 22, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(105, "Itahari", "Janakpur")
            ))
        ));

        registerUser(new UserModel(4, "Diana", "Female", 28, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(106, "Hetauda", "Butwal")
            ))
        ));

        registerUser(new UserModel(5, "Eve", "Female", 35, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(107, "Chitwan", "Kaski"),
                new OrderModel(108, "Dang", "Rupandehi"),
                new OrderModel(109, "Pokhara", "Syangja")
            ))
        ));

        registerUser(new UserModel(6, "Frank", "Male", 40, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(110, "Lumbini", "Tanahu")
            ))
        ));

        registerUser(new UserModel(7, "Grace", "Female", 27, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(111, "Dharan", "Bhadrapur"),
                new OrderModel(112, "Chandrapur", "Lahan")
            ))
        ));

        registerUser(new UserModel(8, "Henry", "Male", 33, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(113, "Pokhara", "Damauli"),
                new OrderModel(114, "Kathmandu", "Bhaktapur")
            ))
        ));

        registerUser(new UserModel(9, "Ivy", "Female", 29, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(115, "Birgunj", "Sunsari"),
                new OrderModel(116, "Kavre", "Sindhuli")
            ))
        ));

        registerUser(new UserModel(10, "Jack", "Male", 23, 
            new ArrayList<>(Arrays.asList(
                new OrderModel(117, "Mahendranagar", "Baitadi"),
                new OrderModel(118, "Ramechhap", "Dolakha")
            ))
        ));
    }

    
    private void registerUser(UserModel user) {
        userList.add(user);
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.addRow(new Object[]{
            user.getUsrId(), user.getUsrName(), user.getUsrSex(),
            user.getUsrAge(), user.getUsrOrders()
        });
    }
    
    private void removeUser(int userID) {
        // Find the user in the list
        UserModel userToRemove = null;
        for (UserModel user : userList) {
            if (user.getUsrId() == userID) {
                userToRemove = user;
                break;
            }
        }

        if (userToRemove != null) {
            // Remove user from the list
            userList.remove(userToRemove);

            // Remove the corresponding row from the table
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if ((int) model.getValueAt(i, 0) == userID) {
                    model.removeRow(i);
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "User removed successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "User not found with ID: " + userID);
        }
    }
    
    private void addUser(int id, String name, String gender, int age, ArrayList<OrderModel> orders) {
        // Create a new user object
        UserModel newUser = new UserModel(id, name, gender, age, orders);

        // Add the user to the list
        userList.add(newUser);

        // Add a new row to the table
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        model.addRow(new Object[]{
            newUser.getUsrId(), newUser.getUsrName(), newUser.getUsrSex(),
            newUser.getUsrAge(), newUser.getUsrOrders()
        });

        JOptionPane.showMessageDialog(null, "User added successfully!");
    }
    
    private void updateUser(int userID, String name, String gender, int age) {
        // Find the user in the list
        UserModel userToUpdate = null;
        for (UserModel user : userList) {
            if (user.getUsrId() == userID) {
                userToUpdate = user;
                break;
            }
        }

        if (userToUpdate != null) {
            // Update the user details
            userToUpdate.setUsrName(name);
            userToUpdate.setUsrSex(gender);
            userToUpdate.setUsrAge(age);

            // Update the corresponding row in the table
            DefaultTableModel model = (DefaultTableModel) userTable.getModel();
            for (int i = 0; i < model.getRowCount(); i++) {
                if ((int) model.getValueAt(i, 0) == userID) {
                    model.setValueAt(name, i, 1);   // Update Name
                    model.setValueAt(gender, i, 2); // Update Gender
                    model.setValueAt(age, i, 3);   // Update Age
                    break;
                }
            }

            JOptionPane.showMessageDialog(null, "User info updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "User not found with ID: " + userID);
        }
    }
    
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Get the username and password from the text fields
        String username = usernameTextField.getText();
        String password = new String(passwordTextField.getPassword()); // For JPasswordField
        boolean isAdmin = adminCheckBox.isSelected(); // Check if the checkbox is selected

        // Validate input
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check login credentials
        if (isAdmin) {
            // Admin credentials
            if (username.equals("admin") && password.equals("password")) {
                // Redirect to admin dashboard or perform admin-specific tasks
                adminPanel.setVisible(true);
                loginPanel.setVisible(false);
                
                JOptionPane.showMessageDialog(this, "Welcome Admin!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid admin credentials!", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // User credentials
            if (username.equals("user") && password.equals("password")) {
                // Redirect to user dashboard or perform user-specific tasks
                userPanel.setVisible(true);
                loginPanel.setVisible(false);
                
                JOptionPane.showMessageDialog(this, "Welcome User!", "Login Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid user credentials!", "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void PickUptextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PickUptextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PickUptextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dropOffTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropOffTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropOffTextFieldActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        userPanel.setVisible(false);
        loginPanel.setVisible(true);
        JOptionPane.showMessageDialog(this, "Logout Successful", "Logging Out", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminCheckBoxActionPerformed

    private void logoutButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButton2ActionPerformed
        // TODO add your handling code here:
        adminPanel.setVisible(false);
        loginPanel.setVisible(true);
        JOptionPane.showMessageDialog(this, "Logout Successful", "Logging Out", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_logoutButton2ActionPerformed

    private void updateInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInfoButtonActionPerformed
        // TODO add your handling code here:
        try {
            // Show input dialogs to get updated user information
            int userID = Integer.parseInt(JOptionPane.showInputDialog("Enter User ID to update:"));
            String name = JOptionPane.showInputDialog("Enter New User Name:");
            String gender = JOptionPane.showInputDialog("Enter New User Gender (Male/Female):");
            int age = Integer.parseInt(JOptionPane.showInputDialog("Enter New User Age:"));

            // Call the updateUser method
            updateUser(userID, name, gender, age);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter valid numeric values for ID and Age.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage());
        }
    }//GEN-LAST:event_updateInfoButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        // TODO add your handling code here:
        try {
            // Show input dialogs to get user information
            int id = Integer.parseInt(JOptionPane.showInputDialog("Enter User ID:"));
            String name = JOptionPane.showInputDialog("Enter User Name:");
            String gender = JOptionPane.showInputDialog("Enter User Gender (Male/Female):");
            int age = Integer.parseInt(JOptionPane.showInputDialog("Enter User Age:"));

            // Optional: Initialize orders (empty for now or customize as needed)
            ArrayList<OrderModel> orders = new ArrayList<>();

            // Call the addUser method
            addUser(id, name, gender, age, orders);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter valid numeric values for ID and Age.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + ex.getMessage());
        }
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void removeUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserButtonActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("Enter User ID to remove:");
        try {
            int userID = Integer.parseInt(input);
            removeUser(userID);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid User ID. Please enter a numeric value.");
        }
    }//GEN-LAST:event_removeUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogisticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogisticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogisticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogisticsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogisticsApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField PickUptextField;
    private javax.swing.JButton addUserButton;
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JPanel credentialPanel;
    private javax.swing.JPanel credentialPanel1;
    private javax.swing.JTextField dropOffTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoIngLabel;
    private javax.swing.JLabel logoIngLabel1;
    private javax.swing.JLabel logoIngLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutButton2;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton removeUserButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JPanel topPanel2;
    private javax.swing.JLabel truckImgLabel;
    private javax.swing.JButton updateInfoButton;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTable userTable;
    private java.awt.TextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
